// Sustainability questions grouped into a structured array
const questions = [
    // Ventilation Rates
    "Analyze the provided images and description to determine if any of the following ventilation scenarios apply to the design. Use the following guidelines as a reference: ASHRAE Guidelines: Focus on airflow rates and the presence of features that promote natural or mechanical ventilation. WELL Standards: Consider elements that ensure good indoor air quality and occupant comfort. LEED Criteria: Look at design choices that contribute to energy efficiency and healthy indoor environments. These guidelines will help you identify whether the design meets the requirements for natural, mixed, or fully mechanical ventilation.",
    "1. Please look at this images and see if the room or building seems to be naturally ventilated. In other words, does it have design features that let fresh air flow in and out easily? For example, check if there are large or well-placed windows, open spaces that encourage airflow, skylights, or high ceilings that help move the air around. These features are similar to what experts recommend for good, healthy air circulation. Does the space seem to have enough of these elements to allow natural ventilation?",
    "2. Please look at the images and see if the space uses both natural and mechanical methods to move air. In other words, does it have features like windows, skylights, or open designs that let in fresh air, combined with elements such as fans, ducts, or air conditioning that help circulate and control the airflow? If you can tell that about half or more of the air comes in naturally, then the space is using a mixed ventilation approach.",
    "3. Please examine the images to determine if the space relies solely on mechanical systems—such as air conditioning units, fans, or ducts—for ventilation. In other words, does the setup seem designed to push in and circulate significantly more fresh air—about 50% above the basic level typically needed for good air quality? Look for visible indicators like extensive ductwork, multiple air vents, or large mechanical systems that might suggest this enhanced airflow.",    
    // Air Quality Control Measures
    "Analyze the provided images and description of the project to determine if any of the following air quality control measures are present in the design:",
    "4. Review the provided images and project documentation to determine whether the space appears to be equipped with a CO₂ monitoring system designed to maintain indoor levels below 800 ppm. While you may not be able to directly measure CO₂ levels from the images, look for visible signs of monitoring equipment—such as digital displays, sensor devices, or control panels—that indicate the presence of a system aimed at ensuring proper ventilation and air quality.",
    "5. Review the provided images and project documentation to determine if the design includes a standalone air-cleaning device that utilizes a carbon filter to treat the air. Look for any dedicated equipment—such as a freestanding or wall-mounted unit—with visible controls or labels indicating it functions as an air purifier. Additionally, check the documentation for any mention of carbon-filter air cleaning systems. Does the available information suggest that this air treatment solution is part of the design?",
    "6. Review the provided images and project documentation to determine if the main air ducts incorporate activated carbon filters—or a combination of particulate and carbon filters—to help purify the air. While these filters may not be directly visible in the images, look for any equipment labels, control panels, or system specifications that mention such filtration components. Does the available information indicate that the air handling system includes these types of filters?",
    // Daylight
    "Review the provided images and project description to assess how the design manages natural light and reduces glare, which can cause visual discomfort. As you evaluate the space, look for features that help control the intensity and direction of sunlight. Specifically, consider the following elements: Shading Devices: External or internal elements like louvers, awnings, or overhangs that block direct sunlight. Window Treatments: Adjustable options such as blinds or curtains that allow fine-tuning of daylight levels. Specialized Glazing: Treated or tinted glass designed to minimize glare. These design choices aim to balance the benefits of natural light with the need for occupant comfort by preventing excessive brightness and heat. Your task is to determine whether these measures are present and appear effective in mitigating glare.",
    "7. Please examine the image and determine if there are any shading devices incorporated to reduce glare. Look for features such as external elements (e.g., louvers, awnings, overhangs) or internal elements that are designed to block direct sunlight. These features should appear to be intentionally placed to control the amount of light entering the space and enhance visual comfort.",
    "8. Please examine the images to see if you can identify any window treatments—such as adjustable blinds, curtains, or similar features—that appear to be designed to control the amount of daylight entering the space. These adjustable elements help manage glare and create a more comfortable indoor environment.",
    "9. Please examine the images and look closely at the windows and other glass surfaces. Are there any indications that the glass is treated or designed to reduce glare—such as a noticeable tint, a low-glare finish, or other specialized features? These modifications are intended to minimize the intensity of sunlight entering the space and enhance visual comfort. Does the design seem to incorporate such specialized glazing?",
    // External Views
    "Review the provided images and project description to assess whether the design effectively connects interior spaces with the outdoors. Look for features such as expansive glass surfaces, unobstructed views, or strategic window placements that allow occupants to visually engage with the external environment.",
    "10. Review the images to assess whether the design provides occupants with clear visual connections to the outdoors through transparent glazing, such as glass facades, windows, or glass walls. In particular, consider if most of the key occupant spaces—like common areas or workspaces—appear to offer unobstructed external views. The goal is for a significant number of occupants to have an opportunity to enjoy these external views, enhancing their overall experience and well-being.",
    // Individual Comfort Control
    "11. Review the provided project images and description to verify that the space is fully enclosed. Fully enclosed buildings are generally equipped with HVAC systems and thermal comforts. Even if individual thermal control features are not clearly visible, confirming that the space is completely enclosed suggests that it is designed for a climate-controlled environment.",
    // Acoustic
    "12. Review the provided images and description to determine if the design incorporates measures to control noise and maintain appropriate acoustic levels for its intended use. Look for acoustic treatments such as sound-absorbing materials, acoustic panels, ceiling baffles, specialized finishes, as well as design elements like dividers or partitions that can help block or absorb sound. Additionally, note if carpeting or other soft floor coverings are used, as these can significantly reduce reverberation and dampen noise levels. Does the design appear to include these elements to meet the acoustic performance requirements for its intended function?",
    //Volatile Organic Compounds (VOC)
    "13. Review the project images and description to assess whether the interior finishes appear to be selected with indoor air quality in mind. Although VOC levels cannot be measured directly from images, look for clues such as mentions of low-VOC paints, adhesives, sealants, or eco-friendly materials in the project documentation. Does the information suggest that the design prioritizes finishes aimed at minimizing the release of volatile organic compounds",
    "14. Review the project documentation and specifications to determine if the interior paint finishes meet low-VOC standards. Specifically, check whether the documentation indicates that the paint used has a VOC content of less than 16 grams per liter (g/L), which helps to ensure improved indoor air quality.",
    "15. Review the project documentation and images to verify whether the carpets installed meet low-emission standards for indoor air quality. Specifically, look for any indication that the carpets comply with the ASTM D5116 standard, which limits VOC emissions to 0.5 mg/m²/hour. Does the available information confirm that the carpet selection is designed to minimize VOC emissions?",
    "16. Review the provided images and project documentation to determine whether engineered wood products are used in the design. Look for visual indicators such as cabinetry, flooring, or other finish elements made from engineered wood. Does the documentation confirm that engineered wood is incorporated as a key material in the project?",
    "17. Review the project documentation and images to verify whether the design specifies trim, varnishes, and wood stains with low VOC content. Although VOC levels cannot be directly observed in images, check for any indications in the documentation that these finishing products have a VOC content of 75 g/L or less, in line with indoor air quality standards. Does the available information confirm that these materials meet the specified low-emission criteria?",
    //Formaldehyde Minimization
    "18. Review the provided images and project documentation to determine if newly installed components are designed to minimize formaldehyde emissions. Although you may not be able to directly observe chemical compositions in the images, look for product specifications, labels, or certification documents that indicate urea-formaldehyde levels are below 100 ppm or that the components comply with local building code requirements for formaldehyde emissions. Does the available information suggest that the design prioritizes materials with controlled formaldehyde content?",
    //Mold Prevention
    "19. Review the provided project images and documentation to determine whether the design incorporates effective measures to prevent moisture intrusion and mold growth. Look for evidence of moisture control elements such as moisture barriers, damp-proof membranes, proper drainage systems, water-resistant materials, and design details that discourage water accumulation on structural surfaces. Does the available information indicate that the building’s structure and fabric are adequately protected against conditions that could lead to mold development?",    
    //Exhaust Systems
    "20. Review the provided images and project documentation to determine if the design includes dedicated exhaust systems in spaces such as kitchens, printer rooms, or washrooms. Look for evidence of localized ventilation features—such as visible exhaust vents, ductwork, or mechanical exhaust fans—that are specifically designed to remove indoor pollutants directly from these areas. Does the available information suggest that these spaces have been equipped with effective direct exhaust systems?",
]

// Export the questions array
module.exports = questions;